export default {
  // Roots
  home: '/',
  login: '/login',
  about: '/about',
  pricing: '/pricing',
  features: '/features',
  dashboard: '/dashboard',
  certifications: '/certifications',
  contests: '/contests',
  contest: '/contest/:contestId',
  contestChallenge: '/contest/:contestId/challenge/:challengeId',
  joinContest: '/join/:contestId',
  jobs: '/jobs',
  challenge: '/challenge/:challengeId',
  bareChallenge: '/challenge',
  bareContest: '/contest',
  challenges: '/challenges',
  administration: '/administration',
  createContest: '/administration/contest/create',
  manageContest: '/administration/contest',
  // Nested Dashboard pages
  settings: '/dashboard/settings',
  profile: '/profile/:username',
};
